---
- hosts: all
  become: true
  remote_user: vagrant
  tasks:
        - name: Execute pre-setting
          include_tasks: preset.yml

        - name: Copy the join command to server location
          copy: src=join-command dest=/tmp/join-command.sh mode=0777

        - name: Join the node to cluster
          command: sh /tmp/join-command.sh
